Lara/pm add cancel with note
postgrid/postgrid-python pull request #14
Opened 2024-03-12 14:57 UTC by laraPostgrid

Added the cancel with note endpoint to letters, postcards and cheques.

Extended DeletableResource to CancellableCollateral with the new endpoint.

2024-03-12 21:23 UTC, laraPostgrid commented
https://linear.app/postgrid/issue/ENG-2890/update-python-sdk-to-add-cancel-with-note-endpoint

2024-03-21 16:45 UTC, goodpaul6 requested changes

2024-04-01 15:34 UTC, goodpaul6 requested changes

2024-04-01 15:34 UTC, goodpaul6 commented on tests/test_cheque.py
> +
Newline at EOF here too; I think running the `black` formatter on all the files should do the trick.

2024-04-03 16:54 UTC, goodpaul6 approved these changes

2024-04-03 16:54 UTC, merged